sudo: required
services:
  - docker
before-install:
  - docker build -t reactapp .
  - gem install rake

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-one"
  env: "DockerReactOne-env"
  bucket_name: "elasticbeanstalk-us-east-1-319068213696"
  bucket_path: "docker-react-one"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_ACCESS_SECRET_KEY